# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [1]:
import numpy as np

### Answer 1

In [3]:
arr = np.random.randint(1,21, size=(5,5))
arr[:, 2] = 1
arr

array([[15, 15,  1,  7,  8],
       [10, 17,  1, 11,  6],
       [ 5, 10,  1, 16, 15],
       [15, 20,  1,  5,  7],
       [18, 17,  1, 16, 16]], dtype=int32)

In [5]:
arr = np.arange(1,17).reshape((4,4))
np.fill_diagonal(arr, 0)
arr

array([[ 0,  2,  3,  4],
       [ 5,  0,  7,  8],
       [ 9, 10,  0, 12],
       [13, 14, 15,  0]])

### Answer 2

In [6]:
arr = np.arange(1,37).reshape((6,6))
print(arr[2:5, 1:4])

[[14 15 16]
 [20 21 22]
 [26 27 28]]


In [13]:
arr = np.random.randint(1,26,size=(5,5))
print(arr)
print(arr[0,:],arr[1:-1,-1], arr[-1,-1::-1], arr[-2:0:-1, 0])

[[15 22  1 17 16]
 [ 6 22 24 23 14]
 [18 18 15 20 13]
 [ 4 25 10  5 16]
 [ 3  2 10 24 10]]
[15 22  1 17 16] [14 13 16] [10 24 10  2  3] [ 4 18  6]


### Answer 3

In [14]:
arr1 = np.random.randint(1,11,size=(3,4))
arr2 = np.random.randint(1,11,size=(3,4))

print(f"a: {arr1}, b: {arr2}")
print(f"sum: {arr1+arr2}")
print(f"diff: {arr1-arr2}")
print(f"prod: {arr1*arr2}")
print(f"div: {arr1/arr2}")

a: [[7 1 5 7]
 [2 4 3 9]
 [4 5 4 6]], b: [[ 9  9  5  9]
 [ 4  1 10  4]
 [ 3  7  1  2]]
sum: [[16 10 10 16]
 [ 6  5 13 13]
 [ 7 12  5  8]]
diff: [[-2 -8  0 -2]
 [-2  3 -7  5]
 [ 1 -2  3  4]]
prod: [[63  9 25 63]
 [ 8  4 30 36]
 [12 35  4 12]]
div: [[0.77777778 0.11111111 1.         0.77777778]
 [0.5        4.         0.3        2.25      ]
 [1.33333333 0.71428571 4.         3.        ]]


In [18]:
arr = np.arange(1,17).reshape((4,4))

print(f"arr: {arr}")
print(f"rowsum: {np.sum(arr,axis=1)}")
print(f"colsum: {np.sum(arr,axis=0)}")


arr: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
rowsum: [10 26 42 58]
colsum: [28 32 36 40]


### Answer 4

In [21]:
arr = np.random.randint(1,21,size=(5,5))
mean = np.mean(arr)
median = np.median(arr)
std = np.std(arr)
var = np.var(arr)
print(arr)
print(f"mean: {mean}\nmedian: {median}\nstd: {std}\nvar: {var}")


[[20  7 18  7 16]
 [15  3 19 15 10]
 [12 18  6  5 14]
 [19 15 19  9  6]
 [18  8 18 13  7]]
mean: 12.68
median: 14.0
std: 5.2818178688781
var: 27.897599999999997


In [23]:
arr = np.arange(1,10).reshape((3,3))
print(f"arr: {arr}")
normalized_arr = (arr-np.mean(arr))/np.std(arr)
print(f"Normalized: {normalized_arr}")

arr: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Normalized: [[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


### Answer 5

In [24]:
arr1 = np.random.randint(1,21,size=(3,3))
arr2 = np.random.randint(1,21,size=(3,))

print("arr: ", arr1)
print("add: ", arr2)
print("res: ", arr1+arr2)

arr:  [[12  4  9]
 [10 13 17]
 [ 9 14 14]]
add:  [ 3 13  6]
res:  [[15 17 15]
 [13 26 23]
 [12 27 20]]


In [28]:
arr1 = np.random.randint(1,21,size=(4,4))
arr2 = np.random.randint(1,21,size=(4,1))

print("arr: ", arr1)
print("sub: ", arr2)
print("res: ", arr1-arr2)

arr:  [[19 18 18 11]
 [17 18 17 10]
 [10 16  9  3]
 [ 1  8  7  1]]
sub:  [[ 5]
 [ 2]
 [15]
 [ 4]]
res:  [[ 14  13  13   6]
 [ 15  16  15   8]
 [ -5   1  -6 -12]
 [ -3   4   3  -3]]


### Answer 6

In [30]:
mat = np.random.randint(1,21,size=(3,3))

print(f"arr: {mat}")
print(f"det: {np.linalg.det(mat)}")
print(f"inv: {np.linalg.inv(mat)}")
print(f"eig: {np.linalg.eigvals(mat)}")


arr: [[19 13  9]
 [ 9 16  9]
 [12 14  8]]
det: -88.00000000000027
inv: [[-0.02272727 -0.25        0.30681818]
 [-0.40909091 -0.5         1.02272727]
 [ 0.75        1.25       -2.125     ]]
eig: [36.56131084  6.79301153 -0.35432236]


In [31]:
m1 = np.random.randint(1,21,size=(2,3))
m2 = np.random.randint(1,21,size=(3,2))

print("m1:",m1)
print("m2:",m2)
print("m1 x m2:", np.linalg.matmul(m1,m2))
print("m2 x m1:", np.linalg.matmul(m2,m1))

m1: [[ 4 14 14]
 [ 2 11  2]]
m2: [[15 11]
 [ 3 20]
 [ 1 14]]
m1 x m2: [[116 520]
 [ 65 270]]
m2 x m1: [[ 82 331 232]
 [ 52 262  82]
 [ 32 168  42]]


### Answer 7

In [32]:
arr = np.arange(1,10).reshape((3,3))
print("original: ", arr)

print("singluar row: ", arr.reshape((1,9)))
print("singluar column: ", arr.reshape((9,1)))

original:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
singluar row:  [[1 2 3 4 5 6 7 8 9]]
singluar column:  [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [33]:
arr = np.random.randint(1,26,size=(5,5))
print("original: ", arr)

flattened = arr.flatten()
print("flattened: ", flattened)

print("reshaped: ", flattened.reshape((5,5)))

original:  [[15 19  9 25 19]
 [15 15  4 19 17]
 [ 3 18 10 11 12]
 [ 1 11  6 16  2]
 [ 2  7 17  9 12]]
flattened:  [15 19  9 25 19 15 15  4 19 17  3 18 10 11 12  1 11  6 16  2  2  7 17  9
 12]
reshaped:  [[15 19  9 25 19]
 [15 15  4 19 17]
 [ 3 18 10 11 12]
 [ 1 11  6 16  2]
 [ 2  7 17  9 12]]


### Answer 8

In [34]:
mat = np.random.randint(1,26,size=(5,5))
print("original: ", mat)

print("corners: ", mat[[0,0,-1,-1],[0,-1,0,-1]])

original:  [[23  6 15 14 24]
 [14 18 17 14 10]
 [ 6  3 13 20  6]
 [16 24 21 14 25]
 [ 5 16  7  3 25]]
corners:  [23 24  5 25]


In [35]:
arr = np.random.randint(1,21,size=(4,4))
print("original: ", arr)

mask = arr>10
arr[mask]=10
print(arr)

original:  [[ 6 20  2  9]
 [20 16 18  3]
 [11  5 18  9]
 [17  2 10 15]]
[[ 6 10  2  9]
 [10 10 10  3]
 [10  5 10  9]
 [10  2 10 10]]


### Answer 9